"""
SadakSathi — Civic Issue Duplicate Detector (v2)

Ported and refactored from eNivaran's duplication_detection_code.py.

Architecture (v2 — XGBoost removed):
  - Image features:    ResNet50 embeddings → cosine similarity (threshold: 0.80)
  - Text features:     Sentence-BERT (paraphrase-MiniLM-L6-v2) → cosine similarity (threshold: 0.70)
  - Geo-proximity:     Haversine distance (geopy) → location score (threshold: 0.10 km gate)
  - Decision:          Weighted combination of per-signal scores with configurable thresholds
                       → No training required, deterministic, fully explainable.

Rationale for removing XGBoost:
  The previous XGBoost classifier was trained on pseudo-labels generated by the same
  weighted formula used in the rule-based fallback. This created a circular training loop
  where XGBoost learned to mimic a formula it was validated against — adding no new
  intelligence. Additionally, XGBoost required ≥10 in-memory reports to activate, but the
  in-memory store was reset on every server restart, meaning it was never actually used in
  production. The new per-signal threshold system is simpler, faster, and more reliable.
"""

from __future__ import annotations

import io
import logging
import os
import warnings
from collections import defaultdict

import numpy as np
from PIL import Image

warnings.filterwarnings("ignore")
logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────
#  Per-Signal Thresholds (tunable via config)
# ─────────────────────────────────────────────

# A report is flagged as duplicate if the WEIGHTED SCORE exceeds DUPLICATE_SCORE_THRESHOLD.
# Weights define signal contribution; adjust based on dataset characteristics.
DEFAULT_IMAGE_WEIGHT     = 0.25   # Image similarity contributes 25%
DEFAULT_TEXT_WEIGHT      = 0.40   # Text description contributes 40%
DEFAULT_LOCATION_WEIGHT  = 0.35   # Geo-proximity contributes 35%

DEFAULT_DUPLICATE_SCORE_THRESHOLD = 0.68  # Combined score ≥ 0.68 → duplicate

# Hard-gate: location must be within this radius for image/text checks to proceed.
# This prevents comparing complaints from completely different cities.
DEFAULT_LOCATION_GATE_KM = 0.10   # 100 metres

# Per-signal explanation thresholds (used for generating the 'signal_breakdown' field)
IMAGE_SIM_STRONG    = 0.85  # Strong visual similarity → almost certainly same scene
TEXT_SIM_STRONG     = 0.80  # Near-identical descriptions
LOCATION_SCORE_HIGH = 0.90  # Within ~10m of the original complaint


def _decode_image_bytes(image_bytes: bytes) -> Image.Image:
    """Decode raw image bytes to a PIL Image."""
    try:
        return Image.open(io.BytesIO(image_bytes)).convert("RGB")
    except Exception as e:
        logger.warning(f"Error decoding image bytes: {e}")
        return Image.new("RGB", (224, 224), color="white")


def _decode_base64_image(base64_str: str) -> Image.Image:
    """Decode a base64 string (with or without data URI prefix) to a PIL Image."""
    import base64 as b64

    try:
        if "," in base64_str:
            base64_str = base64_str.split(",", 1)[1]
        raw = b64.b64decode(base64_str)
        return Image.open(io.BytesIO(raw)).convert("RGB")
    except Exception as e:
        logger.warning(f"Error decoding base64 image: {e}")
        return Image.new("RGB", (224, 224), color="white")


class CivicIssueDuplicateDetector:
    """
    Multi-modal duplicate detection engine using per-signal cosine similarity thresholds.

    Decision pipeline:
    1. Geo-proximity gate  — Skip comparison if location is > location_gate_km away.
    2. Issue type gate     — Skip if issue types differ (prevents cross-class false positives).
    3. Per-signal scoring:
         image_score  = cosine_similarity(ResNet50_emb_A, ResNet50_emb_B)   ∈ [0, 1]
         text_score   = cosine_similarity(SBERT_emb_A,    SBERT_emb_B)      ∈ [0, 1]
         location_score = 1 − min(1, distance_km / location_gate_km)        ∈ [0, 1]
    4. Weighted combination:
         combined = w_img * image_score + w_txt * text_score + w_loc * location_score
    5. Duplicate if combined ≥ duplicate_score_threshold.

    All weights and thresholds are configurable at construction time.
    """

    def __init__(
        self,
        n_clusters: int | None = None,          # Retained for API compatibility (unused)
        location_threshold: float = DEFAULT_LOCATION_GATE_KM,
        text_similarity_threshold: float = 0.65,  # Retained for API compat (used as fallback)
        # New tunable per-signal weights
        image_weight: float = DEFAULT_IMAGE_WEIGHT,
        text_weight: float = DEFAULT_TEXT_WEIGHT,
        location_weight: float = DEFAULT_LOCATION_WEIGHT,
        duplicate_score_threshold: float = DEFAULT_DUPLICATE_SCORE_THRESHOLD,
    ):
        self.location_threshold          = location_threshold   # geo gate in km
        self.text_similarity_threshold   = text_similarity_threshold
        self.image_weight                = image_weight
        self.text_weight                 = text_weight
        self.location_weight             = location_weight
        self.duplicate_score_threshold   = duplicate_score_threshold

        # Validate weights sum to ~1.0
        total = image_weight + text_weight + location_weight
        if not (0.99 <= total <= 1.01):
            logger.warning(
                f"Signal weights sum to {total:.3f} (expected ~1.0). "
                "Scores will be normalised before comparison."
            )
        self._weight_sum = total

        # ── Image feature extractor (ResNet50) ──
        try:
            import torch
            import torchvision.models as models
            import torchvision.transforms as transforms

            resnet = models.resnet50(weights="DEFAULT")
            resnet.eval()
            self.image_model = torch.nn.Sequential(*(list(resnet.children())[:-1]))
            self.image_model_available = True
            logger.info("ResNet50 loaded for image embeddings.")
        except Exception as e:
            logger.warning(f"Could not load ResNet50: {e}. Using histogram fallback.")
            self.image_model = None
            self.image_model_available = False

        try:
            import torchvision.transforms as transforms
            self.image_transform = transforms.Compose([
                transforms.Resize(256),
                transforms.CenterCrop(224),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            ])
        except Exception:
            self.image_transform = None

        # ── Text embedding model (Sentence-BERT) ──
        try:
            from sentence_transformers import SentenceTransformer
            self.text_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")
            self.text_model_available = True
            logger.info("SentenceTransformer loaded for text embeddings.")
        except Exception as e:
            logger.warning(f"Could not load SentenceTransformer: {e}. Using TF-IDF fallback.")
            self.text_model = None
            self.text_model_available = False

        # ── TF-IDF fallback ──
        try:
            from sklearn.feature_extraction.text import TfidfVectorizer
            self.tfidf = TfidfVectorizer(max_features=5000, stop_words="english")
            self.tfidf_fitted = False
        except Exception:
            self.tfidf = None
            self.tfidf_fitted = False

        # ── In-memory database ──
        self.image_features_db: list[np.ndarray]  = []
        self.location_db:       list[list[float]] = []
        self.text_embeddings_db: list[np.ndarray] = []
        self.text_raw_db:       list[str]         = []
        self.issue_types_db:    list[str]         = []
        self.reports_db:        list[dict]        = []

        # Spatial index for fast geo-gating
        self.location_grid: dict = defaultdict(list)

    # ─────────────────────────────────────────
    #  Feature Extraction
    # ─────────────────────────────────────────

    def extract_image_features(self, image_input) -> np.ndarray:
        """Extract image features using ResNet50 (2048-d) or colour histogram fallback (100-d)."""
        try:
            import torch

            if image_input is None:
                return np.zeros(2048 if self.image_model_available else 100)

            # Resolve to PIL Image
            if isinstance(image_input, str):
                if image_input.startswith("data:") or len(image_input) > 500:
                    pil_img = _decode_base64_image(image_input)
                elif os.path.exists(image_input):
                    pil_img = Image.open(image_input).convert("RGB")
                else:
                    return np.zeros(2048 if self.image_model_available else 100)
            elif isinstance(image_input, bytes):
                pil_img = _decode_image_bytes(image_input)
            elif isinstance(image_input, Image.Image):
                pil_img = image_input
            elif isinstance(image_input, np.ndarray):
                pil_img = Image.fromarray(image_input.astype("uint8"))
            else:
                return np.zeros(2048 if self.image_model_available else 100)

            if self.image_model_available and self.image_model is not None and self.image_transform is not None:
                tensor = self.image_transform(pil_img).unsqueeze(0)
                with torch.no_grad():
                    features = self.image_model(tensor)
                return features.squeeze().numpy()
            else:
                # Colour histogram fallback
                arr = np.array(pil_img.resize((64, 64)))
                hist_r = np.histogram(arr[:, :, 0], bins=10, range=(0, 255))[0]
                hist_g = np.histogram(arr[:, :, 1], bins=10, range=(0, 255))[0]
                hist_b = np.histogram(arr[:, :, 2], bins=10, range=(0, 255))[0]
                mean_rgb = np.mean(arr, axis=(0, 1))
                std_rgb = np.std(arr, axis=(0, 1))
                features = np.concatenate([hist_r, hist_g, hist_b, mean_rgb, std_rgb])
                padded = np.zeros(100)
                padded[: len(features)] = features[:100]
                return padded

        except Exception as e:
            logger.warning(f"Image feature extraction error: {e}")
            return np.zeros(2048 if self.image_model_available else 100)

    def extract_text_features(self, text: str) -> np.ndarray:
        """Extract text embeddings using Sentence-BERT (384-d) or TF-IDF fallback."""
        if not text or not isinstance(text, str):
            text = ""

        try:
            if self.text_model_available and self.text_model is not None:
                return self.text_model.encode(text)
            elif self.tfidf is not None:
                if not self.tfidf_fitted and len(self.text_raw_db) > 0:
                    self.tfidf.fit(self.text_raw_db + [text])
                    self.tfidf_fitted = True
                    return self.tfidf.transform([text]).toarray()[0]
                elif self.tfidf_fitted:
                    return self.tfidf.transform([text]).toarray()[0]
            return np.array([len(text), len(text.split())] + [0] * 382)
        except Exception as e:
            logger.warning(f"Text feature extraction error: {e}")
            return np.zeros(384)

    # ─────────────────────────────────────────
    #  Report Management
    # ─────────────────────────────────────────

    def _location_to_grid(self, location: list[float]) -> tuple[int, int]:
        """Map (lat, lon) to a coarse grid cell for O(1) geo-proximity lookup."""
        try:
            # Grid cell size ≈ location_threshold degrees (~11 km at equator)
            grid_size = max(self.location_threshold * 10, 0.01)
            return (int(location[0] / grid_size), int(location[1] / grid_size))
        except Exception:
            return (0, 0)

    def add_report(self, report: dict) -> int | None:
        """
        Add a report to the in-memory index.

        Required keys: text, location ([lat, lon]), issue_type.
        Optional keys: id, image_base64, image_path, image_bytes.
        """
        try:
            for field in ("text", "location", "issue_type"):
                if field not in report:
                    raise ValueError(f"Missing required field: {field}")

            image_input    = report.get("image_base64") or report.get("image_bytes") or report.get("image_path")
            image_features = self.extract_image_features(image_input)
            text_embedding = self.extract_text_features(report["text"])

            idx = len(self.reports_db)
            self.image_features_db.append(image_features)
            self.text_embeddings_db.append(text_embedding)
            self.text_raw_db.append(report["text"])
            self.location_db.append(report["location"])
            self.issue_types_db.append(report["issue_type"])
            self.reports_db.append(report)

            grid = self._location_to_grid(report["location"])
            self.location_grid[grid].append(idx)

            return idx

        except Exception as e:
            logger.error(f"Error adding report: {e}")
            return None

    # ─────────────────────────────────────────
    #  Per-Signal Scoring
    # ─────────────────────────────────────────

    def _cosine_similarity(self, a: np.ndarray, b: np.ndarray) -> float:
        """Compute cosine similarity between two 1-D numpy vectors. Returns 0.0 on error."""
        try:
            norm_a = np.linalg.norm(a)
            norm_b = np.linalg.norm(b)
            if norm_a == 0 or norm_b == 0:
                return 0.0
            val = float(np.dot(a, b) / (norm_a * norm_b))
            return max(0.0, min(1.0, val))   # Clamp to [0, 1]
        except Exception:
            return 0.0

    def _compute_location_score(self, loc_a: list[float], loc_b: list[float]) -> tuple[float, float]:
        """
        Compute geo-proximity score ∈ [0, 1] and raw distance in km.
        Score = 1.0 means same location; 0.0 means at or beyond the gate radius.
        """
        try:
            import geopy.distance
            dist_km = geopy.distance.distance(loc_a, loc_b).kilometers
            score   = 1.0 - min(1.0, dist_km / self.location_threshold)
            return score, dist_km
        except Exception as e:
            logger.warning(f"Geo-distance error: {e}")
            return 0.0, float("inf")

    def _compute_combined_score(
        self,
        image_score: float,
        text_score: float,
        location_score: float,
    ) -> float:
        """
        Compute the weighted combined duplicate score.
        Normalises weights to sum to 1.0 if they don't already.
        """
        raw = (
            self.image_weight    * image_score +
            self.text_weight     * text_score  +
            self.location_weight * location_score
        )
        return raw / self._weight_sum   # Normalise in case weights don't sum exactly to 1.0

    def _signal_explanation(
        self,
        image_score: float,
        text_score: float,
        location_score: float,
        combined: float,
    ) -> dict:
        """Generate human-readable per-signal breakdown for API response."""
        return {
            "image_similarity":    round(image_score,    4),
            "text_similarity":     round(text_score,     4),
            "location_score":      round(location_score, 4),
            "combined_score":      round(combined,       4),
            "threshold":           self.duplicate_score_threshold,
            "strong_image_match":  image_score    >= IMAGE_SIM_STRONG,
            "strong_text_match":   text_score     >= TEXT_SIM_STRONG,
            "very_close_location": location_score >= LOCATION_SCORE_HIGH,
        }

    # ─────────────────────────────────────────
    #  Duplicate Detection
    # ─────────────────────────────────────────

    def find_duplicates(self, new_report: dict) -> tuple[bool, list[dict], float, list[dict]]:
        """
        Check if a new report duplicates any existing report.

        Returns:
            (is_duplicate, list_of_similar_reports, best_confidence, signal_breakdowns)

        Algorithm:
          For each existing report of the same issue_type within location_gate_km:
            1. Compute image_score  (cosine similarity of ResNet50 embeddings)
            2. Compute text_score   (cosine similarity of SBERT embeddings)
            3. Compute location_score (1 - normalised distance)
            4. combined = w_img*img + w_txt*txt + w_loc*loc
            5. If combined ≥ duplicate_score_threshold → flag as duplicate
        """
        try:
            for field in ("text", "location", "issue_type"):
                if field not in new_report:
                    logger.warning(f"Missing field: {field}")
                    return False, [], 0.0, []

            image_input  = new_report.get("image_base64") or new_report.get("image_bytes") or new_report.get("image_path")
            new_img_feat = self.extract_image_features(image_input)
            new_txt_emb  = self.extract_text_features(new_report["text"])
            new_loc      = new_report["location"]
            new_type     = new_report["issue_type"]

            matches: list[tuple[dict, float, dict]] = []   # (report, combined_score, breakdown)

            for idx, report in enumerate(self.reports_db):
                try:
                    # Gate 1: Issue type must match
                    if report.get("issue_type") != new_type:
                        continue

                    # Gate 2: Location must be within the geo gate
                    location_score, dist_km = self._compute_location_score(new_loc, self.location_db[idx])
                    if dist_km > self.location_threshold:
                        continue    # Too far — skip expensive embedding comparisons

                    # Per-signal cosine similarities
                    image_score = self._cosine_similarity(new_img_feat, self.image_features_db[idx])
                    text_score  = self._cosine_similarity(new_txt_emb,  self.text_embeddings_db[idx])

                    # Weighted combination
                    combined = self._compute_combined_score(image_score, text_score, location_score)

                    if combined >= self.duplicate_score_threshold:
                        breakdown = self._signal_explanation(image_score, text_score, location_score, combined)
                        matches.append((report, combined, breakdown))

                except Exception as e:
                    logger.warning(f"Comparison error with report {idx}: {e}")
                    continue

            # Sort by confidence descending
            matches.sort(key=lambda x: x[1], reverse=True)

            if matches:
                best_reports    = [r for r, _, _  in matches]
                best_confidence = matches[0][1]
                breakdowns      = [b for _, _, b in matches]
                return True, best_reports, best_confidence, breakdowns

            return False, [], 0.0, []

        except Exception as e:
            logger.error(f"find_duplicates error: {e}")
            return False, [], 0.0, []

    def process_json_input(self, data: dict) -> dict:
        """
        Process a report dict and return duplicate status with signal breakdown.

        Returns:
            {
                "is_duplicate": 0|1,
                "original_report_id": "...",
                "confidence": float,
                "signal_breakdown": { image_similarity, text_similarity, location_score, combined_score, ... },
                "similar_reports": [...]
            }
        """
        try:
            is_dup, similar, confidence, breakdowns = self.find_duplicates(data)
            response: dict = {
                "is_duplicate": 1 if is_dup else 0,
                "confidence":   round(confidence, 4),
            }

            if is_dup and similar:
                original_ids = [r.get("id") for r in similar if r.get("id")]
                if original_ids:
                    response["original_report_id"] = original_ids[0]

                # Include the best signal breakdown for transparency
                if breakdowns:
                    response["signal_breakdown"] = breakdowns[0]

                response["similar_reports"] = [
                    {
                        "id":         r.get("id", "unknown"),
                        "text":       (r.get("text", "")[:100] + "...") if len(r.get("text", "")) > 100 else r.get("text", ""),
                        "issue_type": r.get("issue_type", ""),
                        "location":   r.get("location", []),
                    }
                    for r in similar[:5]
                ]

            return response

        except Exception as e:
            logger.error(f"process_json_input error: {e}")
            return {"is_duplicate": 0, "error": str(e)}

    # ─────────────────────────────────────────
    #  Cluster building (retained for API compat)
    # ─────────────────────────────────────────

    def build_clusters(self):
        """
        Optional: Build KMeans clusters from all stored image features.
        Not required for duplicate detection — retained for compatibility.
        """
        from sklearn.cluster import KMeans

        try:
            if len(self.reports_db) < 2:
                return
            n = max(2, min(len(self.reports_db) // 2, 50))
            n = min(n, len(self.reports_db))
            kmeans = KMeans(n_clusters=n, random_state=42, n_init=10)
            kmeans.fit(np.array(self.image_features_db))
            logger.info(f"KMeans clustering complete ({n} clusters).")
        except Exception as e:
            logger.error(f"Error building clusters: {e}")


def create_detector(**kwargs) -> CivicIssueDuplicateDetector:
    """Factory function to create a configured detector instance."""
    try:
        detector = CivicIssueDuplicateDetector(**kwargs)
        logger.info(
            f"Duplicate detector initialised (v2 — per-signal thresholds). "
            f"Weights: image={detector.image_weight}, text={detector.text_weight}, "
            f"location={detector.location_weight}, threshold={detector.duplicate_score_threshold}"
        )
        return detector
    except Exception as e:
        logger.error(f"Error creating detector: {e}")
        raise
